from io import BytesIO
from pathlib import Path
import re

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.section import WD_SECTION
from docx.shared import Inches, Pt
from fpdf import FPDF

from utils.text_utils import sanitize_text


def _split_lines(text: str):
    return [line.strip() for line in sanitize_text(text).split("\n")]


def format_docx(text: str, doc_type: str) -> bytes:
    doc = Document()
    section = doc.sections[0]
    section.top_margin = Inches(0.75)
    section.bottom_margin = Inches(0.75)
    section.left_margin = Inches(0.85)
    section.right_margin = Inches(0.85)

    styles = doc.styles
    styles["Normal"].font.name = "Times New Roman"
    styles["Normal"].font.size = Pt(11)

    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run(doc_type.upper())
    run.bold = True
    run.font.name = "Times New Roman"
    run.font.size = Pt(16)

    for line in _split_lines(text):
        if not line:
            continue

        # Treat common numbered headings and all-caps headings as headings.
        is_heading = bool(
            re.match(r"^\d+[\.\)]\s+\S+", line)
            or (line.isupper() and len(line) < 100)
        )

        if is_heading:
            p = doc.add_paragraph()
            r = p.add_run(line)
            r.bold = True
            r.font.name = "Times New Roman"
            r.font.size = Pt(12)
        elif line.startswith("- "):
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(line[2:])
        else:
            p = doc.add_paragraph(line)
        p.paragraph_format.space_after = Pt(6)
        p.paragraph_format.line_spacing = 1.15

    footer = section.footer.paragraphs[0]
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.add_run("Generated by LegalEase - AI-assisted draft. Review before use.")

    buffer = BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


class LegalEasePDF(FPDF):
    def __init__(self, doc_type: str):
        super().__init__()
        self.doc_type = doc_type
        self.set_auto_page_break(auto=True, margin=18)

    def header(self):
        self.set_font("Helvetica", "B", 12)
        self.cell(0, 8, "LegalEase", align="C")
        self.ln(8)
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 7, self.doc_type, align="C")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(
            0,
            8,
            f"Generated by LegalEase - AI-assisted draft | Page {self.page_no()}",
            align="C",
        )


def format_pdf(text: str, doc_type: str) -> bytes:
    pdf = LegalEasePDF(doc_type)
    pdf.add_page()
    pdf.set_font("Helvetica", size=11)

    for line in _split_lines(text):
        if not line:
            pdf.ln(3)
            continue

        is_heading = bool(
            re.match(r"^\d+[\.\)]\s+\S+", line)
            or (line.isupper() and len(line) < 100)
        )

        if is_heading:
            pdf.set_font("Helvetica", "B", 11)
            pdf.multi_cell(0, 6, line)
            pdf.set_font("Helvetica", size=11)
        elif line.startswith("- "):
            pdf.multi_cell(0, 6, "• " + line[2:])
        else:
            pdf.multi_cell(0, 6, line)
        pdf.ln(1)

    return bytes(pdf.output(dest="S"))


def format_html_preview(text: str) -> str:
    from utils.text_utils import html_escape

    blocks = []
    for line in _split_lines(text):
        if not line:
            blocks.append("<div class='spacer'></div>")
        elif line.startswith("- "):
            blocks.append(f"<div class='bullet'>• {html_escape(line[2:])}</div>")
        elif re.match(r"^\d+[\.\)]\s+\S+", line) or (
            line.isupper() and len(line) < 100
        ):
            blocks.append(f"<h3>{html_escape(line)}</h3>")
        else:
            blocks.append(f"<p>{html_escape(line)}</p>")

    return "\n".join(blocks)
